-- MySQL Script generated by MySQL Workbench
-- dim. 01 avril 2018 18:34:05 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema checkpoint1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema checkpoint1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint1` DEFAULT CHARACTER SET utf8 ;
USE `checkpoint1` ;

-- -----------------------------------------------------
-- Table `checkpoint1`.`civility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint1`.`civility` ;

CREATE TABLE IF NOT EXISTS `checkpoint1`.`civility` (
  `id` INT(11) NOT NULL,
  `civility` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checkpoint1`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint1`.`contact` ;

CREATE TABLE IF NOT EXISTS `checkpoint1`.`contact` (
  `id` INT(11) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `civility_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_civility_idx` (`civility_id` ASC),
  CONSTRAINT `fk_contact_civility`
    FOREIGN KEY (`civility_id`)
    REFERENCES `checkpoint1`.`civility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
